# fly.toml app configuration file generated for crypto-price-alert on 2023-11-19T11:37:16+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crypto-price-alert"
primary_region = "sin"

[build]
dockerfile = "Dockerfile"
build-target = "runtime"

[env]
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
